### ISSUE TITLE
support for typescript

### ISSUE THREAD

**Issue by bsorrentino** [caffeinalab/preferences#3]
Hi, I'm using your great library.

I develop using typescript, so would be great to have a **typescript definition** for such library

I've created a proposal [here](https://gist.github.com/bsorrentino/d77f53958783155bd3b832cbba79b03f) and I'd to know if it is possible pushing it to npm following the procedure described [here](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

Thanks in Advance

**Comment by lastguest** [comment]
Hi, can you open a pull request for the modification requested in this topic?

**Comment by berdon** [comment]
Should be addressed by #7
