### ISSUE TITLE
Provide way to overwrite Preferences

### ISSUE THREAD

**Issue by jonavila** [caffeinalab/preferences#4]
I'm creating a CLI tool where I would like to give users the ability to overwrite their stored config options. Is there a way to overwrite the data?

**Comment by lastguest** [comment]
Just modify the config value, the module will save on files at process exit.

Look at the example in the README, change the last `console.log(prefs.account)` to `console.log(prefs)` and look for the `prefs.test.cycles` variable being incremented at every run.

**Comment by psumstr** [comment]
@lastguest Could this be the problem?
```  // If supported observe object for saving on modify
  if (Object.observe) Object.observe(self, save)```

I believe Object.Observe was deprecated, so the save will not get called when the preferences already exist.

**Comment by lastguest** [comment]
You are right. :(
The class needs some refactor to permit the fallback. I'll do as soon as I can.
Thanks for pointing this out.

**Comment by berdon** [comment]
#8 provides a potential workaround by being able to use prefs.clear().
